#!/bin/bash
# trap ctrl-c to restore the 'haproxy.cfg' settings.
trap ctrl_c INT

function ctrl_c() {
		sudo cp /etc/haproxy/Atstart_haproxy.cfg /etc/haproxy/haproxy.cfg
		for i in "${containerInstances[@]}"
		do
			check=$(sudo docker stop $i)
		done
		echo "Haproxy Settings Restored !!"
		exit 0
}

#Scaling thresholds
high_threshold=40
low_threshold=5
containerInstances=()
inum=2
while true; do
	cpuUsage=()
	cpuUsage=( $(sudo docker stats --no-stream | awk '{print $2}') )
	echo ${cpuUsage[@]:1}
	for i in "${cpuUsage[@]:1}"
		do
			cur_cpu=${i::-1}
			cmp=$(echo "$cur_cpu>$high_threshold" | bc)
			echo "Decision Value : $cmp"
			if [ $cmp -eq 1 ];
			then
				echo "Instantiating new container...."
				inum=$(echo "$inum+1"|bc)
				CID=$(sudo docker run -d -it my-apache2)
				containerInstances+=($CID)
				new_ip=()
				new_ip=($(sudo docker inspect $CID | grep IPAddress | cut -d '"' -f 4))
				add_id="             server $inum-www ${new_ip[1]}:80 check"
				sudo echo $add_id >> /etc/haproxy/haproxy.cfg
				result=$(sudo systemctl reload haproxy)
				break
			fi
		done
		sleep 1
done
