#!/bin/bash

# trap ctrl-c to restore the 'haproxy.cfg' settings.
trap ctrl_c INT

function ctrl_c() {
		sudo cp /etc/haproxy/Atstart_haproxy.cfg /etc/haproxy/haproxy.cfg
		echo "Haproxy Settings Restored !!"
}

#Scaling thresholds
high_threshold=50
low_threshold=20
inum=2
while true; do
	cpuUsage=()
	cpuUsage=( $(sudo docker stats --no-stream | awk '{print $2}') )
	#echo ${cpuUsage[@]:1}
	for i in "${cpuUsage[@]:1}"
		do
			cur_cpu=${i::-1}
			cmp=$(echo "$cur_cpu>$threshold" | bc)
			if [ $cmp -eq 1 ];
			then
				inum=$(echo "$inum+1"|bc)
				CID=$(sudo docker run -d --name running_apache$inum --rm -it my-apache2)
				new_ip=$(sudo docker inspect $CID)
				add_id="             server $inum-www $new_ip:80 check"
				sudo echo $add_ip >> /etc/haproxy/haproxy.cfg
				sudo systemctl restart haproxy.service
			fi
	sleep 2
		done
done
